### ISSUE TITLE
Contract and Test Milestones

### ISSUE THREAD

**Issue by greenlucid** [greenlucid/raila#14]
### Tasks
- [x] https://github.com/greenlucid/raila/issues/3
- [x] https://github.com/greenlucid/raila/issues/4
- [x] https://github.com/greenlucid/raila/issues/7
- [x] https://github.com/greenlucid/raila/issues/10
- [x] https://github.com/greenlucid/raila/issues/12
- [x] https://github.com/greenlucid/raila/issues/15
- [ ] https://github.com/greenlucid/raila/issues/13
- [x] https://github.com/greenlucid/raila/issues/17
- [x] https://github.com/greenlucid/raila/issues/18
